export const translate = {
  "Esteghlal Mollasani": "استقلال ملاسانی",
  "Arman Gohar": "آرمان گوهر",
  "Pars Jonoubi JAM": "پارس جنوبی جم",
  "Astara": "آستارا",
  "Kheybar Khorramabad": "خیبر خرم آباد",
  "Mes Kerman": "مس کرمان",
  "Khooshe Talaee": "خوشه طلایی",
  "Qashqai Shiraz": "قشقاقی شیراز",
  "Malavan": "ملوان",
  "Vista Turbine": "ویستاتوربین",
  "Mes Shahr-e Babak": "مس شهر بابک",
  "Baderan Tehran": "بادران تهران",
  "Machine Sazi FC": "ماشین سازی",
  "Shahin Bushehr": "شاهین بوشهر",
  "Saipa": "سایپا",
  "Khooshe Talaee Saveh": "خوشه طلایی ساوه",
  "Rayka Babol": "ریکا بابل",
  "Shahrdari Astara": "شهرداری آستارا",
  "Shahrdari Hamedan": "شهرداری همدان",
  "Shams Azar Qazvin": "شمس آذر قزوین",
  "Aluminium Arak": "آلومینیوم اراک",
  "Mes Rafsanjan": "مس رفسنجان",
  "Naft Masjed Soleyman": "نفت مسجد سلیمان",
  "Fajr Sepasi": "فجر سپاسی",
  "Gol Gohar": "گل گوهر",
  "Nassaji Mazandaran": "نساجی مازندران",
  "Esteghlal FC": "استقلال",
  "Foolad FC": "فولاد",
  "Tractor Sazi": "تراکتور سازی",
  "ZOB Ahan": "ذئب آهن",
  "Padideh Khorasan": "پدیده خراسان",
  "Paykan": "پیکان",
  "Persepolis FC": "پرسپولیس",
  "Sanat Naft": "صنعت نفت",
  "Sepahan FC": "سپاهان",
  "Havadar": "هوادار",
  "Azadegan League": "لیگ دسته یک آزادگان",
  "Persian Gulf Cup": "لیگ برتر خلیج فارس",
  "Esteghlal Khuzestan": "استقلال خوزستان"
};
