import Head from 'next/head'
import Image from 'next/image'
import Header from '../container/Layout/Header'
import MatchComp from '../components/MatchComp'
import { persianDate } from "../server/data";


export default function Home() {
  return (
    <main>
      <Head>
        <title>Footballi App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MatchComp gamesData={persianDate[1]}/>
    </main>
  )
}
